apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: vmsingle, namespace: argoproj }
spec:
  project: default
  source:
    chart: victoria-metrics-single
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.9.0
    helm:
      parameters:
        - name: server.persistenceVolume.size
          value: "10Gi"
        - name: server.resources.requests.memory
          value: "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncPolicy: [CreateNamespace=true]
