apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idp-tls
  namespace: default
spec:
  secretName: idp-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.attalea.pw
    - tm-api.attalea.pw
    - tm.attalea.pw
