---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: observability
spec:
  encryptedData:
    admin-password: AgA1mpeG6MZK+iCHjgVA2oSNY275BWPVfKXG7KugR+tivKJIgnmn9Bij6H936e0UteKkhfP0lhR9j30pzL4fl4HXbus5j8owHBKi1WXEISnYm5F7RsHrfdTNhiZm6JvrHKBvpHh+EvihCvu4k9eBXS5mP+1OfCBwZTXE1Kl7ancYZkHwSa24PNcXoUSpblGTn47aBJS8kUh2lK/u3HQWhbPu+rYXPOdLswLOnxlZ1hamkoAJBZZHVHWKk/cNbfCbAxwB2sd56EIpf/fYLiM+Cvow+W3rQivHoyTbaz7KGuSPGVbnkoSscSaN9H4HMDp/br2puynnHTAxm4+NeVIfz2VjY7Krthw6ccbMxcCslaEf7RYJ9oIMai/DeiZtmXuED9qJP/3e2WUVui82i7GG30lfvPBT/zZ3oSukuzt4beANxHJyJLuzD7oEgEYUnwnoQMapja1bIjcWuZpO8AZqqlVizyyHO9vGJt8GyF/iVQrpB4fgvHUUuwrufc2IPDc/GQVCghBx5fN/lbSrcaAyL9mK8z/6CGfGUsOsnaWOb042m+Rz+P3p8YjHeK4aO+4ZvQFtcBdFisubYPL0wIgloN4coFLXYrjKUZvHmiX/z3z3o1qXayKPZqBVUk2QaRFM9BrFEBR6Wgmau8KAtHAUtv7ej8ANUw4KlbWCVfNDw0gTp4w3pd4U1TAxlQJIlK+k0gFPHWXBtkTH5v1J5/0=
    admin-user: AgAqs9fvIGDAnfCeZ7Qfxihtc19MK6++bDU9Xk6yeNTG5FqCZZDxVyMjrfRkEjEXJPgrHucQzFiCmLm0FSuCZQO19RILVKATYLQ3PjK+fvqB1d9Ct4z0Xg3a6oKrN5kJ2L70tAXXmd9D3CS5y4j2vv76mRpB/nX5F++p+Dcd+T4nFRb1HFA4ueOZXPkIaTzOamUqVo4QSCWdYPGlNZErUGiMYSjwta3yr07EBl1OpwROeddwLynRVlNWFB7yd/0zYUBrxdjqoab8a8dkqT3AyTZCN7ABOJj7/juMIIS0ykJNMz7nplEGhK+3dT56GLGq6glFBP2mp8KHXl2KuFrUfRaUqkdt6ErCC1JdkpZbP2ZrkW+O7XvK9g5iuIJ0g+hb/nvCrRpybhhCyg2QbHllnWLiNA2+8lyppFi+BFovQfci+v5xh9RNQNh2kjq85xI5oZkhMwEdpAvlo/5iym2d5HPkhcy8Dv0uwZOg7FVnJbFlFUaqe0mwhm9XBIsAUMv4kvlW6ubyydeyzpdH7+HR1CcHIFqBBQkF/fwy+KYG2S5jZJL66pwy/G/0sOqbs28x39KP92QLwUuBsFz7bBMNRgkjucDEj7haU1F2Aqbvug6gVaA9hONyyy4TZoFbTsYI9Y35JHbuautN2uSWZlRAu4VKEHslLxQrLRqHg/6EFgyNyDC5DdBzJmD1wpxieQBAW8r6mrp3jw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: observability
    type: Opaque
