---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: observability
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgCsomGzcQZXvJTZDU4Rs6CngRI9YkbTR9Lj8YI5sfdikuLpLThMm8n0kBqT+yhzL/vsiMuEzu0+8e6w1HemW4ktypriyVYIk6/BWUCMqd+1+wyE8hNNGgIWGQgw8dWXMuowVXFEasA7OMCzvPSGA5ZCTKcqiwsm9lsvWG7MwI8/8QgMHG7zUXfmjb2g/q3e2pGzxYGLRMDddi6tmuM68+SAG843o+5kPhCGVKt4r4vR3k+majgnf4vwRXKWnEfw5mqhitKxV90qRBoqc+ihYejqzfECi+8UflYqBxBcjI15JaH8RE/w0gquzp//dY0kMFT9n7G3+YijGdGTyvh8mT+wdWhWqgT84RYtibQTkIRbI7sTcq2+eO/j+zjX+u5JOn7xJhG3HJg80HYtQti5fJv/voP54CCc2GoXGhBqBsmq8uXJO3uS1RV8ocYNAuwn50jXwZ4DMVCwl2S8iboQE6jQ+SsWSjxEBBBvmYSvg9fjh9M7tdBlqiCwO5FT7srF3fwXrklnU9CdhJZAXdVmBqPgHR+mTBKjT0pxvwOarHGGRvqto9dfCWsQ14C7gX7grQ+JMlqrgDGW9vZDeJRqaZzJhmp5NpBtBlyu1iPaq8FCJChudkn+fRZSeDsAkY4Le3ZfbmUQ0QKLTPpYQT9Yx8qFU68HpsnvBKI3aJldbSlaQiIXbSXua0HPELWa+sasjnt6YbZL93ZLsW9Y/n4=
    GRAFANA_ADMIN_USER: AgAzVI6PF/E+6QbXqBzOivx6T8AyCRUPn4gE5rttbG9IZgA8lwFTUZXryPjKZpV/qKQN0iLyrUq0H6qsz4TKWWCkF+GcX0gCMXDFl091ut7teRbin/mMmDNS+/miOpA+dyxstHWY/NyTUmJqHM93m3G3MrBzbcab9C6lC2ePH+09YUIBTAq/zrA9OFtyrjs1SOij61GzgJiSJIR6lDFzkRJv0Jo46NZgtD7xYSRWLBVzQSGwVHyr2x1wvrT4Uyier+4fi3S43jGzi7pniXn9siwv2qe/ZbMBwulIVaP7YzFDtbx7fs7c6LzLhq1Bh9eKK2riVHAg2oHUAf3YKYXAQGKiyiOpoii8GRTgWDRF7DkRMPDwWqkdf6ReMSZAK68Mw3diHJwB6nOULtON1FZ4d1IvQ6EKdyirnJ6ZY3uz/J3rBbxoYZsKzH4FOmIp2xoiE8m9r5cwwfglcVwzbD8UrMy5+DhCbEJghiaqzqEfxZYZTbomUm2i1Pive2iyTOFk+HToYW5pp0AUDWCg5aZpsFfrG/zq69AYRD2S/Iy+LLXXRKmm6+QexOPLx3nZOT+kiD5A+mWw7mi1M4fBSNqu9b2+AJ0WkTtJwYW+3udZw96MmK+AwbZ9aPpxz4voxZ1PR7fLLGnJXvX5+AdzhKnt6hvxOOCYKcIXNrUfh9Y2qcwPd+R/NApBux9lUYR3TjmemzhPr99Aag==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: observability
    type: Opaque
