apiVersion: v1
kind: ConfigMap
metadata:
  name: quickwit-config
  namespace: observability
data:
  quickwit.yaml: |
    version: 0.7.0
    metastore_uri: s3://ca9df933fb84-attalea-cloud-s3/quickwit/metastore
    default_index_root_uri: s3://ca9df933fb84-attalea-cloud-s3/quickwit/indexses
    storage:
      s3:
        endpoint: https://s3.ru1.storage.beget.cloud
        region: ru-central1
