apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickwit
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickwit
  template:
    metadata:
      labels:
        app: quickwit
    spec:
      containers:
        - name: quickwit
          image: quickwit/quickwit:v0.9.0
          args: ["run"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secret
                  key: S3_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secret
                  key: S3_SECRET_ACCESS_KEY
            - name: QW_CONFIG
              value: /config/quickwit.yaml
          ports:
            - containerPort: 7280
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
      volumes:
        - name: config
          configMap:
            name: quickwit-config
