apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: The team building the IDP
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: "attalea"
spec:
  profile:
    displayName: Attalea
    email: "attaleastingray@mail.ru"
  memberOf:
    - platform-team
