apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-frontend
  labels:
    app: task-manager-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-frontend
  template:
    metadata:
      labels:
        app: task-manager-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "64Mi"
          env:
            - name: VITE_API_URL
              value: "https://tm-api.attalea.pw"
