helm:
  parameters:
  - name: image.repository
    value: ghcr.io/attaleast/idp-task-manager-frontend-demo
    forcestring: false
  - name: image.name
    value: ghcr.io/attaleast/idp-task-manager-frontend-demo
    forcestring: true
  - name: image.tag
    value: sha-f10ac112132d21f721fe9d0a9515d891133fbef1
    forcestring: true
