helm:
  parameters:
  - name: image.repository
    value: ghcr.io/attaleast/idp-task-manager-frontend-demo
    forcestring: false
  - name: image.name
    value: ghcr.io/attaleast/idp-task-manager-frontend-demo
    forcestring: true
  - name: image.tag
    value: sha-37855a8b4ce5faebfa39eb384b3903918d9a0140
    forcestring: true
