apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: gateway-config, namespace: argocd }
spec:
  project: default
  source:
    repoURL: https://github.com/attaleast/idp-platform.git
    path: manifests/gateway
    targetRevision: HEAD
  destination:
    server: https://kubernetest.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /status
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /status
