apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: { prune: true, seflHeal: true }
    syncOptions:
      - CreateNamespace=true
