apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: postgresql, namespace: argocd }
spec:
  project: default
  source:
    repoURL: https://github.com/attaleast/idp-platform.git
    targetRevision: HEAD
    path: manifests/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
