apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: loki, namespace: argocd }
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.0
    helm:
      parameters:
        - name: deploymentMode
          value: "SingleBinary"
        - name: singleBinary.replicas
          value: "1"
        - name: singleBinary.resources.requests.memory
          value: "128Mi"

        - name: read.replicas
          value: "0"
        - name: write.replicas
          value: "0"
        - name: backend.replicas
          value: "0"

        - name: backend.type
          value: "filesystem"
        - name: loki.useTestSchema
          value: "true"

        - name: loki.storage.bucketNames.chunks
          value: ${S3_BUCKET}
        - name: loki.storage.bucketNames.ruler
          value: ${S3_BUCKET}
        - name: loki.storage.bucketNames.admin
          value: ${S3_BUCKET}
        - name: loki.storage.s3.endpoint
          vaule: ${S3_ENDPOINT}
        - name: loki.storage.s3.region
          value: ${S3_REGION}
        - name: loki.storage.s3.accessKeyId
          vaule: ${S3_ACCESS_KEY}
        - name: loki.storage.s3.secretAccessKey
          value: ${S3_SECRET_KEY}

        - name: chunksCache.enabled
          value: "false"
        - name: resultsCache.enabled
          value: "false"

        - name: gateway.enabled
          value: "false"

        - name: singleBinary.extraEnvFrom
          value: '[{"secretRef": {"name": "s3-secret"}}]'
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
