apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.0
    helm:
      values: |
        deploymentMode: SingleBinary

        loki:
          commonConfig:
            replication_factor: 1
          useTestSchema: true
          storage:
            bucketNames:
              chunks: ca9df933fb84-attalea-cloud-s3
              ruler: ca9df933fb84-attalea-cloud-s3
              admin: ca9df933fb84-attalea-cloud-s3
            s3:
              endpoint: https://s3.ru1.storage.beget.cloud
              region: ru-central-1

        singleBinary:
          replicas: 1
          resources:
            requests:
              memory: 128Mi
        extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: S3_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: S3_SECRET_KEY
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        gateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
