apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=ghcr.io/attaleast/idp-task-manager-demo
    argocd-image-updater.argoproj.io/myalias.allow-tags: regexp:^latest$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:Image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/attaleast/idp-platform.git
    targetRevision: HEAD
    path: apps/task-manager
    helm:
      parameters:
        - name: image.repository
          value: "ghcr.io/attaleast/idp-task-manager-demo"
  destination:
    server: https://kubernetes.default.svc
    namespace: ecosystem
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
