apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/attaleast/idp-task-manager-demo.git
    targetRevision: HEAD
    path: helm/task-manager/templates
    helm:
      parameters:
        - name: image.tag
          value: "a90a35b3380b4dc9bda9071a74e9481e63d56c2b"
  destination:
    server: https://kubernetes.default.svc
    namespace: ecosystem
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
