apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 1.2.0
    helm:
      values: |
        nats:
          jetstream:
            enabled: true
            memStorage:
              enabled: true
              size: 128Mi
            fileStorage:
              enabled: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
