apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 1.2.0
    helm:
      parameters:
        - name: nats.jetstream.enabled
          value: "true"
        - name: nats.jetstream.fileStorage.enabled
          value: "false"
        - name: nats.jetstream.memStorage.enabled
          value: "true"
        - name: nats.jetstream.memStorage.size
          value: "128Mi"
        - name: nats.resources.requests.memory
          value: "64Mi"
        - name: nats.resources.requests.cpu
          value: "50m"
        - name: nats.resources.limits.memory
          value: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
