apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.0
    helm:
      values: |
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
        config:
          clients:
            - url: http://quickwit.observability.svc.cluster.local:7280/api/v1/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
