---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: observability
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgB6WldJC8gSmXbabiu/gHyfwHpuLtqYKeGgxN22omqHqRHiJT6J+ow8C+q9mMb/JFN0x33JkiLi4hYgErE/JDoDTIAhbbAiMq96tjqG0mrqlMjpKg+2/CCxvGW10lsbO8s+E7mnwKRAiogv+qh2v8ZivJ9T2TIzDO7x6j5JY1E0XenZM+xs+txf7zCtpZ8t07CcCVvAvB9LfAzvFtKmk1cNMpHBwKzUil5I0UInhSjWcFjBnsTHVDSGsrry+ID1iZANai2n6DVb+XY4vugp6kjd0oOhNAs/rKvX9s44ZAmU2aXj0M/KAtQb/ph1qM61YmLs2HJ7SHI08hsCOu4SOlvqh5P6CLX3mQf/vPkbKyBS4JXDSaK0nq3hqi2MFT+V9WQH2SIdg3wNDuGXKBDsawedmvtuEwigNP3JpkJ/7hDvIwNxwibpXLfV7uRUI4JFchxcuoZ7UAjeuMk18KeQ6BmWB/7Tqx5YiIK7ef0JS72r4bfQOUomjo7kyUtTEzNpFkmBGVjoqhlZbTjlBUAEWanNuO/3eYPAw3uhj2QhfB1r4vFHYhNh2VCd1S754qY9NexO1H/SMmw9egpIAm3Wxg37T0ScgJmbjPMmRv+38YG8sO4FoMT3H9gp57OaWHFgyvmhqPprrDi/b2cWWMQLCb/UkjyMblT2vdBAyz8U1KXcqnvhgWWBLNFm8mdpP4wIFXzWy6kMDOUe0et4GsQ=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: observability
    type: Opaque
